### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by MrBrowner** [girishg4t/bhavCopy-downloader#31]
Cloned the project & ran successfully.
but, when i tried to download a file.

i got this in console.
```
Cross-Origin Request Blocked: 
The Same Origin Policy disallows reading the remote resource 
at https://bhavcopy-backend.fly.dev/getbhavcopy. 
(Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Status code: 200.
```

why so ?

Thanks.

**ps: it's my first time coding a web project**

**Comment by MrBrowner** [comment]
okay. 
After some search, i got to know is:

we have to define `"Access-Control-Allow-Origin", "*"` in the header.

**Comment by girishg4t** [comment]
In the backend we need to allow that header, but * is not recommended.
you have to run the backend on your local as well for this 

or you can call this api's directly from you local
https://bhavcopy-backend.fly.dev/

**Comment by MrBrowner** [comment]
The URL is already defined in config.url.

how so ? where/what to make changes ?

can please help me to setup it.

Thanks & Regards.

**Comment by girishg4t** [comment]
@MrBrowner 
How to run the application on local
1) clone the repo
2) do `npm install`
3) `npm start`
4) when you click download you will get CORS error, for that install cors extension in your browser and enable it, in my case in Firefox i am using 
```
CORS Everywhere
Bypass CORS restrictions by altering http responses.
```
similar kind of extensions will exists in Chrome 


let me know if you want to contribute and want to get some idea on project, we can have a call as well

**Comment by MrBrowner** [comment]
@girishg4t 
Thank you very much.

as i was stuck on pt.4. Now it's able do api call successfully
also, there is a warning in console
`Attempt to set a forbidden header was denied: Origin`

& yes, I'm happy to make contribution to the project, we can have a scheduled call on gmeet?

**Comment by girishg4t** [comment]
Sure, schedule a call. i am mostly available as i am doing WFH

**Comment by MrBrowner** [comment]
hey.
was setting-up multi ssh keys, totally confusing.. at last it accepted the commit.

we can have meet today ?

**Comment by girishg4t** [comment]
we can check today

**Comment by MrBrowner** [comment]
@girishg4t 
what time should we schedule a gmeet?
 I'm available.

**Comment by girishg4t** [comment]
Before 4 pm today is fine, also please share your email id
my is talekar.g@gmail.com

**Comment by MrBrowner** [comment]
Yes, shared the meet link on email.

**Comment by girishg4t** [comment]
@MrBrowner i have pinged you on gmail, let's connect when both are available

**Comment by MrBrowner** [comment]
We can connect now.

**Comment by girishg4t** [comment]
YES
