### ISSUE TITLE
nse eod file: extra info present on 1st line

### ISSUE THREAD

**Issue by MrBrowner** [girishg4t/bhavCopy-downloader#35]
Hey, Hi @girishg4t,

I just downloaded the nse eod data .
And in some files their seems to be some extra info/data present at the 1st line.

`
Not a valid date format, it should be in ddMMMYYYY format, eg. 02Mar2020SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES,ISIN,
`

> Not a valid date format, it should be in ddMMMYYYY format, eg. 02Mar2020

This is present in whole july 2023 month eod files.

**Comment by girishg4t** [comment]
Hi @MrBrowner,
Could you please give me the sample file and comparision with other files

**Comment by MrBrowner** [comment]
okay.

[nse-All-2023-07-03.csv](https://github.com/girishg4t/bhavCopy-downloader/files/13346382/nse-All-2023-07-03.csv)
[nse-All-2023-08-10.csv](https://github.com/girishg4t/bhavCopy-downloader/files/13346384/nse-All-2023-08-10.csv)

ref: in July month file's the 1st line.

**Comment by girishg4t** [comment]
@MrBrowner if you see the fle 03-JUL-2023 and TimeStamp field it is showing the correct date format
https://github.com/girishg4t/nse-bse-bhavcopy/blob/master/nse/03JUL2023.csv

this is the file it get downloaded

**Comment by MrBrowner** [comment]
Yea, looks like the issue is something else.
